screensize = 1600, 900
FPS = 60  # Setting the target frames per second
gamestartlvl = 'Foyer'  # Setting the current game level
doors = []  # List to hold the doors
walls = []  # List to hold the walls
mobs = []  # List to hold the enemies
killed = []  # List to hold the dead, do not sign up for this list
mousex = 0  # Used to store x coordinate of mouse event
mousey = 0  # Used to store y coordinate of mouse event
gamerunning = True
mouseClicked = False
backgroundImage = None
